before_install:
  - bundle

env:
  # Don't run GUI specs on Travis, as the server is headless and
  # doesn't have the UI dependencies installed.
  - RSPEC_TAGS="~gui"

rvm:
  - 1.9.3
  - 2.0.0

install:
  - sudo add-apt-repository -y ppa:limparissoft/opencv-ppa
  - sudo apt-get -y update
  - sudo apt-get -y install pkg-config opencv
