before_install:
  - bundle

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

install:
  - sudo add-apt-repository -y ppa:limparissoft/opencv-ppa
  - sudo apt-get -y update
  - sudo apt-get -y install pkg-config opencv
